server:
  port: 8081
  address: 127.0.0.1

spring:
  application:
    name: rag-assistant

  docker:
    compose:
      enabled: true
      file: compose.yml
      lifecycle-management: start-and-stop
      skip-in-tests: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:ragdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true
        table-name: vector_store

    ollama:
      base-url: ${OLLAMA_BASE_URL:http://127.0.0.1:11434}

      embedding:
        options:
          model: nomic-embed-text

      chat:
        options:
          model: gemma:2b

rag:
  retrieval:
    top-k: 4
    similarity-threshold: 0.60

  chunking:
    chunk-size: 800
    chunk-overlap: 100
